
export const APP_INIT_REQUEST = 'APP_INIT_REQUEST'
export const APP_INIT_SUCCESS = 'APP_INIT_SUCCESS'
export const APP_INIT_FAILURE = 'APP_INIT_FAILURE'
export type APP_INIT_REQUEST = typeof APP_INIT_REQUEST
export type APP_INIT_SUCCESS = typeof APP_INIT_SUCCESS
export type APP_INIT_FAILURE = typeof APP_INIT_FAILURE

export const LOGIN_REQUEST = 'LOGIN_REQUEST'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_FAILURE = 'LOGIN_FAILURE'
export type LOGIN_REQUEST = typeof LOGIN_REQUEST
export type LOGIN_SUCCESS = typeof LOGIN_SUCCESS
export type LOGIN_FAILURE = typeof LOGIN_FAILURE


export const SIGNUP_REQUEST = 'SIGNUP_REQUEST'
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS'
export const SIGNUP_FAILURE = 'SIGNUP_FAILURE'
export type SIGNUP_REQUEST = typeof SIGNUP_REQUEST
export type SIGNUP_SUCCESS = typeof SIGNUP_SUCCESS
export type SIGNUP_FAILURE = typeof SIGNUP_FAILURE


export const GET_USER_INFO_REQUEST = 'GET_USER_INFO_REQUEST'
export const GET_USER_INFO_SUCCESS = 'GET_USER_INFO_SUCCESS'
export const GET_USER_INFO_FAILURE = 'GET_USER_INFO_FAILURE'
export type GET_USER_INFO_REQUEST = typeof GET_USER_INFO_REQUEST
export type GET_USER_INFO_SUCCESS = typeof GET_USER_INFO_SUCCESS
export type GET_USER_INFO_FAILURE = typeof GET_USER_INFO_FAILURE



export const CHANGE_LOADING_STATUS = 'CHANGE_LOADING_STATUS'
export type CHANGE_LOADING_STATUS = typeof CHANGE_LOADING_STATUS


export const GET_TOKEN_FROM_CACHE = 'GET_TOKEN_FROM_CACHE'
export type GET_TOKEN_FROM_CACHE = typeof GET_TOKEN_FROM_CACHE


export const RESET_STORE = 'RESET_STORE'
export type RESET_STORE = typeof RESET_STORE


export const CHANGE_COLLAPSED='CHANGE_COLLAPSED'
export type CHANGE_COLLAPSED = typeof CHANGE_COLLAPSED



//project 
export const GET_PROJECT_LIST_REQUEST = 'GET_PROJECT_LIST_REQUEST'
export const GET_PROJECT_LIST_SUCCESS = 'GET_PROJECT_LIST_SUCCESS'
export const GET_PROJECT_LIST_FAILURE = 'GET_PROJECT_LIST_FAILURE'
export type GET_PROJECT_LIST_REQUEST = typeof GET_PROJECT_LIST_REQUEST
export type GET_PROJECT_LIST_SUCCESS = typeof GET_PROJECT_LIST_SUCCESS
export type GET_PROJECT_LIST_FAILURE = typeof GET_PROJECT_LIST_FAILURE