export const LOGIN_REQUEST = 'LOGIN_REQUEST'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_FAILURE = 'LOGIN_FAILURE'
export type LOGIN_REQUEST = typeof LOGIN_REQUEST
export type LOGIN_SUCCESS = typeof LOGIN_SUCCESS
export type LOGIN_FAILURE = typeof LOGIN_FAILURE