import { boardReducer } from './../store/reducers/board.reducer';
export const APP_INIT_REQUEST = 'APP_INIT_REQUEST';
export const APP_INIT_SUCCESS = 'APP_INIT_SUCCESS';
export const APP_INIT_FAILURE = 'APP_INIT_FAILURE';
export type APP_INIT_REQUEST = typeof APP_INIT_REQUEST;
export type APP_INIT_SUCCESS = typeof APP_INIT_SUCCESS;
export type APP_INIT_FAILURE = typeof APP_INIT_FAILURE;

export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';
export type LOGIN_REQUEST = typeof LOGIN_REQUEST;
export type LOGIN_SUCCESS = typeof LOGIN_SUCCESS;
export type LOGIN_FAILURE = typeof LOGIN_FAILURE;

export const SIGNUP_REQUEST = 'SIGNUP_REQUEST';
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';
export const SIGNUP_FAILURE = 'SIGNUP_FAILURE';
export type SIGNUP_REQUEST = typeof SIGNUP_REQUEST;
export type SIGNUP_SUCCESS = typeof SIGNUP_SUCCESS;
export type SIGNUP_FAILURE = typeof SIGNUP_FAILURE;

export const GET_USER_INFO_REQUEST = 'GET_USER_INFO_REQUEST';
export const GET_USER_INFO_SUCCESS = 'GET_USER_INFO_SUCCESS';
export const GET_USER_INFO_FAILURE = 'GET_USER_INFO_FAILURE';
export type GET_USER_INFO_REQUEST = typeof GET_USER_INFO_REQUEST;
export type GET_USER_INFO_SUCCESS = typeof GET_USER_INFO_SUCCESS;
export type GET_USER_INFO_FAILURE = typeof GET_USER_INFO_FAILURE;

export const GET_USER_LIST_REQUEST = 'GET_USER_LIST_REQUEST';
export const GET_USER_LIST_SUCCESS = 'GET_USER_LIST_SUCCESS';
export const GET_USER_LIST_FAILURE = 'GET_USER_LIST_FAILURE';

export const CHANGE_LOADING_STATUS = 'CHANGE_LOADING_STATUS';
export type CHANGE_LOADING_STATUS = typeof CHANGE_LOADING_STATUS;

export const GET_TOKEN_FROM_CACHE = 'GET_TOKEN_FROM_CACHE';
export type GET_TOKEN_FROM_CACHE = typeof GET_TOKEN_FROM_CACHE;

export const RESET_STORE = 'RESET_STORE';
export type RESET_STORE = typeof RESET_STORE;

export const CHANGE_COLLAPSED = 'CHANGE_COLLAPSED';
export type CHANGE_COLLAPSED = typeof CHANGE_COLLAPSED;

//project
export const GET_PROJECT_LIST_REQUEST = 'GET_PROJECT_LIST_REQUEST';
export const GET_PROJECT_LIST_SUCCESS = 'GET_PROJECT_LIST_SUCCESS';
export const GET_PROJECT_LIST_FAILURE = 'GET_PROJECT_LIST_FAILURE';
export type GET_PROJECT_LIST_REQUEST = typeof GET_PROJECT_LIST_REQUEST;
export type GET_PROJECT_LIST_SUCCESS = typeof GET_PROJECT_LIST_SUCCESS;
export type GET_PROJECT_LIST_FAILURE = typeof GET_PROJECT_LIST_FAILURE;

export const ADD_PROJECT_REQUEST = 'ADD_PROJECT_REQUEST';
export const ADD_PROJECT_SUCCESS = 'ADD_PROJECT_SUCCESS';
export const ADD_PROJECT_FAILURE = 'ADD_PROJECT_FAILURE';

export const DELETE_PROJECT_REQUEST = 'DELETE_PROJECT_REQUEST';
export const DELETE_PROJECT_SUCCESS = 'DELETE_PROJECT_SUCCESS';
export const DELETE_PROJECT_FAILURE = 'DELETE_PROJECT_FAILURE';

export const GET_PROJECT_REQUEST = 'GET_PROJECT_REQUEST';
export const GET_PROJECT_SUCCESS = 'GET_PROJECT_SUCCESS';
export const GET_PROJECT_FAILURE = 'GET_PROJECT_FAILURE';

export const UPDATE_PROJECT_REQUEST = 'UPDATE_PROJECT_REQUEST';
export const UPDATE_PROJECT_SUCCESS = 'UPDATE_PROJECT_SUCCESS';
export const UPDATE_PROJECT_FAILURE = 'UPDATE_PROJECT_FAILURE';

//metadata
export const GET_METADATA_LIST_REQUEST = 'GET_METADATA_LIST_REQUEST';
export const GET_METADATA_LIST_SUCCESS = 'GET_METADATA_LIST_SUCCESS';
export const GET_METADATA_LIST_FAILURE = 'GET_METADATA_LIST_FAILURE';

export const GET_ACTIVE_METADATA_LIST_REQUEST = 'GET_ACTIVE_METADATA_LIST_REQUEST';
export const GET_ACTIVE_METADATA_LIST_SUCCESS = 'GET_ACTIVE_METADATA_LIST_SUCCESS';
export const GET_ACTIVE_METADATA_LIST_FAILURE = 'GET_ACTIVE_METADATA_LIST_FAILURE';

export const ADD_METADATA_REQUEST = 'ADD_METADATA_REQUEST';
export const ADD_METADATA_SUCCESS = 'ADD_METADATA_SUCCESS';
export const ADD_METADATA_FAILURE = 'ADD_METADATA_FAILURE';

export const DELETE_METADATA_REQUEST = 'DELETE_METADATA_REQUEST';
export const DELETE_METADATA_SUCCESS = 'DELETE_METADATA_SUCCESS';
export const DELETE_METADATA_FAILURE = 'DELETE_METADATA_FAILURE';

export const UPDATE_METADATA_REQUEST = 'UPDATE_METADATA_REQUEST';
export const UPDATE_METADATA_SUCCESS = 'UPDATE_METADATA_SUCCESS';
export const UPDATE_METADATA_FAILURE = 'UPDATE_METADATA_FAILURE';

export const ENABLE_METADATA_REQUEST = 'ENABLE_METADATA_REQUEST';
export const ENABLE_METADATA_SUCCESS = 'ENABLE_METADATA_SUCCESS';
export const ENABLE_METADATA_FAILURE = 'ENABLE_METADATA_FAILURE';

export const DISABLE_METADATA_REQUEST = 'DISABLE_METADATA_REQUEST';
export const DISABLE_METADATA_SUCCESS = 'DISABLE_METADATA_SUCCESS';
export const DISABLE_METADATA_FAILURE = 'DISABLE_METADATA_FAILURE';

export const GET_TAG_LIST_REQUEST = 'GET_TAG_LIST_REQUEST';
export const GET_TAG_LIST_SUCCESS = 'GET_TAG_LIST_SUCCESS';
export const GET_TAG_LIST_FAILURE = 'GET_TAG_LIST_FAILURE';

export const ADD_TAG_REQUEST = 'ADD_TAG_REQUEST';
export const ADD_TAG_SUCCESS = 'ADD_TAG_SUCCESS';
export const ADD_TAG_FAILURE = 'ADD_TAG_FAILURE';

export const DELETE_TAG_REQUEST = 'DELETE_TAG_REQUEST';
export const DELETE_TAG_SUCCESS = 'DELETE_TAG_SUCCESS';
export const DELETE_TAG_FAILURE = 'DELETE_TAG_FAILURE';

export const UPDATE_TAG_REQUEST = 'UPDATE_TAG_REQUEST';
export const UPDATE_TAG_SUCCESS = 'UPDATE_TAG_SUCCESS';
export const UPDATE_TAG_FAILURE = 'UPDATE_TAG_FAILURE';

export const GET_FIELD_LIST_REQUEST = 'GET_FIELD_LIST_REQUEST';
export const GET_FIELD_LIST_SUCCESS = 'GET_FIELD_LIST_SUCCESS';
export const GET_FIELD_LIST_FAILURE = 'GET_FIELD_LIST_FAILURE';

export const GET_ACTIVE_FIELD_LIST_REQUEST = 'GET_ACTIVE_FIELD_LIST_REQUEST';
export const GET_ACTIVE_FIELD_LIST_SUCCESS = 'GET_ACTIVE_FIELD_LIST_SUCCESS';
export const GET_ACTIVE_FIELD_LIST_FAILURE = 'GET_ACTIVE_FIELD_LIST_FAILURE';

//form
export const SAVE_ADD_PROJECT_FORM = 'SAVE_ADD_PROJECT_FORM';

//board
export const GET_BOARD_LIST_REQUEST = 'GET_BOARD_LIST_REQUEST';
export const GET_BOARD_LIST_SUCCESS = 'GET_BOARD_LIST_SUCCESS';
export const GET_BOARD_LIST_FAILURE = 'GET_BOARD_LIST_FAILURE';

export const ADD_BOARD_REQUEST = 'ADD_BOARD_REQUEST';
export const ADD_BOARD_SUCCESS = 'ADD_BOARD_SUCCESS';
export const ADD_BOARD_FAILURE = 'ADD_BOARD_FAILURE';

export const UPDATE_BOARD_REQUEST = 'UPDATE_BOARD_REQUEST';
export const UPDATE_BOARD_SUCCESS = 'UPDATE_BOARD_SUCCESS';
export const UPDATE_BOARD_FAILURE = 'UPDATE_BOARD_FAILURE';

export const DELETE_BOARD_REQUEST = 'DELETE_BOARD_REQUEST';
export const DELETE_BOARD_SUCCESS = 'DELETE_BOARD_SUCCESS';
export const DELETE_BOARD_FAILURE = 'DELETE_BOARD_FAILURE';

export const GET_BOARD_INFO_REQUEST = 'GET_BOARD_INFO_REQUEST';
export const GET_BOARD_INFO_SUCCESS = 'GET_BOARD_INFO_SUCCESS';
export const GET_BOARD_INFO_FAILURE = 'GET_BOARD_INFO_FAILURE';

export const APPEND_REPORT_TO_BOARD_REQUEST = 'APPEND_REPORT_TO_BOARD_REQUEST';
export const APPEND_REPORT_TO_BOARD_SUCCESS = 'APPEND_REPORT_TO_BOARD_SUCCESS';
export const APPEND_REPORT_TO_BOARD_FAILURE = 'APPEND_REPORT_TO_BOARD_FAILURE';

export const DELETE_REPORT_OF_BOARD_REQUEST = 'DELETE_REPORT_OF_BOARD_REQUEST';
export const DELETE_REPORT_OF_BOARD_SUCCESS = 'DELETE_REPORT_OF_BOARD_SUCCESS';
export const DELETE_REPORT_OF_BOARD_FAILURE = 'DELETE_REPORT_OF_BOARD_FAILURE';

export const GET_MY_BOARD_LIST_REQUEST = 'GET_MY_BOARD_LIST_REQUEST';
export const GET_MY_BOARD_LIST_SUCCESS = 'GET_MY_BOARD_LIST_SUCCESS';
export const GET_MY_BOARD_LIST_FAILURE = 'GET_MY_BOARD_LIST_FAILURE';

export const CHENGE_GLOBAL_DATE = 'CHENGE_GLOBAL_DATE';

//report
export const GET_REPORT_LIST_REQUEST = 'GET_REPORT_LIST_REQUEST';
export const GET_REPORT_LIST_SUCCESS = 'GET_REPORT_LIST_SUCCESS';
export const GET_REPORT_LIST_FAILURE = 'GET_REPORT_LIST_FAILURE';

export const GET_REPORT_INFO_REQUEST = 'GET_REPORT_INFO_REQUEST';
export const GET_REPORT_INFO_SUCCESS = 'GET_REPORT_INFO_SUCCESS';
export const GET_REPORT_INFO_FAILURE = 'GET_REPORT_INFO_FAILURE';

export const ADD_REPORT_REQUEST = 'ADD_REPORT_REQUEST';
export const ADD_REPORT_SUCCESS = 'ADD_REPORT_SUCCESS';
export const ADD_REPORT_FAILURE = 'ADD_REPORT_FAILURE';

export const UPDATE_REPORT_REQUEST = 'UPDATE_REPORT_REQUEST';
export const UPDATE_REPORT_SUCCESS = 'UPDATE_REPORT_SUCCESS';
export const UPDATE_REPORT_FAILURE = 'UPDATE_REPORT_FAILURE';

export const DELETE_REPORT_REQUEST = 'DELETE_REPORT_REQUEST';
export const DELETE_REPORT_SUCCESS = 'DELETE_REPORT_SUCCESS';
export const DELETE_REPORT_FAILURE = 'DELETE_REPORT_FAILURE';

export const RESET_REPORT_INFO = 'RESET_REPORT_INFO';

//team
export const GET_TEAM_LIST_REQUEST = 'GET_TEAM_LIST_REQUEST';
export const GET_TEAM_LIST_SUCCESS = 'GET_TEAM_LIST_SUCCESS';
export const GET_TEAM_LIST_FAILURE = 'GET_TEAM_LIST_FAILURE';

export const GET_TEAM_INFO_REQUEST = 'GET_TEAM_INFO_REQUEST';
export const GET_TEAM_INFO_SUCCESS = 'GET_TEAM_INFO_SUCCESS';
export const GET_TEAM_INFO_FAILURE = 'GET_TEAM_INFO_FAILURE';

export const ADD_TEAM_REQUEST = 'ADD_TEAM_REQUEST';
export const ADD_TEAM_SUCCESS = 'ADD_TEAM_SUCCESS';
export const ADD_TEAM_FAILURE = 'ADD_TEAM_FAILURE';

export const DELETE_TEAM_REQUEST = 'DELETE_TEAM_REQUEST';
export const DELETE_TEAM_SUCCESS = 'DELETE_TEAM_SUCCESS';
export const DELETE_TEAM_FAILURE = 'DELETE_TEAM_FAILURE';

export const UPDATE_TEAM_REQUEST = 'UPDATE_TEAM_REQUEST';
export const UPDATE_TEAM_SUCCESS = 'UPDATE_TEAM_SUCCESS';
export const UPDATE_TEAM_FAILURE = 'UPDATE_TEAM_FAILURE';

//analyse
export const EVENT_ANALYSE_REQUEST = 'EVENT_ANALYSE_REQUEST';
export const EVENT_ANALYSE_SUCCESS = 'EVENT_ANALYSE_SUCCESS';
export const EVENT_ANALYSE_FAILURE = 'EVENT_ANALYSE_FAILURE';

export const INIT_ANALYSE = 'INIT_ANALYSE';

export const FUNNEL_ANALYSE_REQUEST = 'FUNNEL_ANALYSE_REQUEST';
export const FUNNEL_ANALYSE_SUCCESS = 'FUNNEL_ANALYSE_SUCCESS';
export const FUNNEL_ANALYSE_FAILURE = 'FUNNEL_ANALYSE_FAILURE';
